import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ClientOnly from "../components/ClientOnly";
import Login from '../components/Login'
import Athentification from '../components/Authentication';
import { useAuth } from './api/auth';

const Home: NextPage = () => {
  const { isSignedIn } = useAuth()
   
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <main className={styles.main}>
      <ClientOnly>
          <Athentification/>
        </ClientOnly>
      </main>
    </div>
  )
  
}
export default Home
